@startuml Packages
!theme plain

package "cine" {
    class Cine
}

package "peliculas" {
    class Pelicula
    class Idioma
}

package "salas" {
    class Sala
    class Butaca
}

package "funciones" {
    class Funcion
}

package "clientes" {
    class Cliente
    class Reserva
}

package "facturacion" {
    class Factura
    class DetalleReserva
}

' Relaciones entre paquetes
cine --> peliculas
cine --> salas
cine --> funciones
cine --> clientes
cine --> facturacion

@enduml
